export const properties = ({ title, description, URL_SITE, IMAGE }) => [
  {
    property: "og:url",
    content: URL_SITE,
  },
  {
    property: "og:title",
    content: title,
  },
  {
    property: "og:description",
    content: description,
  },
  {
    property: "og:image",
    content: IMAGE,
  },
  {
    property: "og:type",
    content: "website",
  },
  {
    property: "twitter:url",
    content: URL_SITE,
  },
  {
    property: "twitter:title",
    content: title,
  },
  {
    property: "twitter:description",
    content: description,
  },
  {
    property: "twitter:image",
    content: IMAGE,
  },
];
export const keywords = [
  "Ecuador Quito",
  "Quito",
  "Ecuador",
  "Programador ecuador",
  "Programador Quito",
  "programador quito",
  "Tecnologia Quito",
  "Tecnología Quito",
  "Desarrollador Quito",
  "Desarrollador Ecuador",
  "Desarrollador Quito Ecuador",
  "Desarrollador freelancer ecuador",
  "Desarrollador freelancer Ecuador",
  "Desarrollador freelancer quito",
  "Desarrollador freelancer Quito Ecuador",
  "Desarrollador react Quito Ecuador",
  "Desarrollador React Quito Ecuador",
  "Desarrollador react native Quito Ecuador",
  "Desarrollador React Native Quito Ecuador",
  "Desarrollador frondent Quito Ecuador",
  "Desarrollador Frondent Quito Ecuador",
  "Desarrollador backent Quito Ecuador",
  "Desarrollador Backent Quito Ecuador",
  "Desarrollador Firebase Quito Ecuador",
  "Desarrollador Google Quito Ecuador",
  "Desarrollador firebase Quito Ecuador",
  "Programador Quito Ecuador",
  "Programador freelancer ecuador",
  "Programador freelancer Ecuador",
  "Programador freelancer quito",
  "Programador freelancer Quito Ecuador",
  "Programador react Quito Ecuador",
  "Programador React Quito Ecuador",
  "Programador react native Quito Ecuador",
  "Programador React Native Quito Ecuador",
  "Programador frondent Quito Ecuador",
  "Programador Frondent Quito Ecuador",
  "Programador backent Quito Ecuador",
  "Programador Backent Quito Ecuador",
  "Programador Firebase Quito Ecuador",
  "Programador Google Quito Ecuador",
  "Programador firebase Quito Ecuador",
  "freelancer react Quito Ecuador",
  "freelancer React Quito Ecuador",
  "freelancer react native Quito Ecuador",
  "freelancer React Native Quito Ecuador",
  "freelancer frondent Quito Ecuador",
  "freelancer Frondent Quito Ecuador",
  "freelancer backent Quito Ecuador",
  "freelancer Backent Quito Ecuador",
  "freelancer Firebase Quito Ecuador",
  "freelancer Google Quito Ecuador",
  "freelancer firebase Quito Ecuador",
];
